// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWk2NX7cB2tgqnRgL1Rb1W5udG8rpRgws',
    appId: '1:754865869864:web:fff4ad724182bb9e7c911d',
    messagingSenderId: '754865869864',
    projectId: 'atiqlo',
    authDomain: 'atiqlo.firebaseapp.com',
    storageBucket: 'atiqlo.firebasestorage.app',

    measurementId: 'G-ZN3VKCB0QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUUGLHuhJGTy6WLBA5Lny7ntQyBbRYFM0',
    appId: '1:754865869864:android:794d29ae4320499b7c911d',
    messagingSenderId: '754865869864',
    projectId: 'atiqlo',
    storageBucket: 'atiqlo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4OZdr28Cd1GvkNZV5D5Ku3InvVU2fqbY',
    appId: '1:754865869864:ios:547ae9ff0f2bcf087c911d',
    messagingSenderId: '754865869864',
    projectId: 'atiqlo',
    storageBucket: 'atiqlo.firebasestorage.app',
    iosBundleId: 'com.example.atiqlo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4OZdr28Cd1GvkNZV5D5Ku3InvVU2fqbY',
    appId: '1:754865869864:ios:547ae9ff0f2bcf087c911d',
    messagingSenderId: '754865869864',
    projectId: 'atiqlo',
    storageBucket: 'atiqlo.firebasestorage.app',
    iosBundleId: 'com.example.atiqlo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWk2NX7cB2tgqnRgL1Rb1W5udG8rpRgws',
    appId: '1:754865869864:web:3dac7b94b56451db7c911d',
    messagingSenderId: '754865869864',
    projectId: 'atiqlo',
    authDomain: 'atiqlo.firebaseapp.com',
    storageBucket: 'atiqlo.firebasestorage.app',
    measurementId: 'G-L450D1HY5Y',
  );
}
